spring:
  application:
    name: messenger

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/messenger_db
    username: messenger_admin
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true

    open-in-view: true

server:
  error:
    include-message: always

logging:
  file:
    name: messenger.log